#发现服务(eureka)地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8012/eureka
  instance:
    hostname: localhost
server:
  port: 8988
spring:
  application:
    name: microservices-config
  profiles:
    active: develop
  cloud:
    config:
      server:
        git:
          uri: https://github.com/antelop304/springcloud-config.git
#          uri: http://root@192.168.1.142:82/base-framework/framework-microservices.git
#          searchPaths: framework-microservices-config/config-repo/*
#          username: huangjing
#          password: huangjing
